import { createContext } from "react";
import { v4 as uuidv4 } from "uuid";

let Dataproduct = createContext([
  {
    id: 1,
    category: "WomenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9igzce8KZlERMQ9NbVZIAvKIt8vEBjTdHAQ&s`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 2,
    category: "WomenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLHkbMIsqBZW7fF8bKOHs9J9tt3rnHS09d2Q&s`,
    lowPrice: 58.99,
    heightPrice: 180,
  },
  {
    id: 3,
    category: "WomenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG-SxV7AafzYd6ieqog3z46yBZY-GiFr8KLg&s`,
    lowPrice: 88.99,
    heightPrice: 280,
  },
  {
    id: 4,
    category: "WomenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://media.johnlewiscontent.com/i/JohnLewis/ww-block18-130625-v1?fmt=auto`,
    lowPrice: 60.99,
    heightPrice: 200,
  },
  {
    id: 5,
    category: "ChildrenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUvcflpTU2usyY1MyEIdAKRVY9aan5TLRUdQ&s`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 6,
    category: "ChildrenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQSIFiZV4Ilmw2fYpNZapuE5p9GfyBiMidSw&s`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 7,
    category: "ChildrenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi6INEBUZyDIAzV62RAEn-DwO4qSTbuYQbnw&s`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 8,
    category: "ChildrenCatalogue",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://img.joomcdn.net/2ef8229072c4e45fe2eec7841730f07a82a30aa0_original.jpeg`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 9,
    category: "Men",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 10,
    category: "Men",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://i.pinimg.com/236x/94/1e/b7/941eb773d4de289124497ece181f3d9d.jpg`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 11,
    category: "Men",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9QFutiU9xa23VqhTo5zoe-b4Ie5ND2b9-CqF761_RrDe94YcDL7SaW_VYI5qwuNFQOAY&usqp=CAU`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 12,
    category: "Men",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRotpjgfwJc8fw7E51ZPn_YfYyETN5xHujgaw&s`,
    lowPrice: 77,
    heightPrice: 180,
  },
  {
    id: 13,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9QFutiU9xa23VqhTo5zoe-b4Ie5ND2b9-CqF761_RrDe94YcDL7SaW_VYI5qwuNFQOAY&usqp=CAU`,
    lowPrice: 32.31,
    heightPrice: 78.67,
  },
  {
    id: 14,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRotpjgfwJc8fw7E51ZPn_YfYyETN5xHujgaw&s`,
    lowPrice: 32.31,
    heightPrice: 78.67,
  },
  {
    id: 15,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 78.67,
  },
  {
    id: 16,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 17,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://i.pinimg.com/236x/94/1e/b7/941eb773d4de289124497ece181f3d9d.jpg`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 18,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9QFutiU9xa23VqhTo5zoe-b4Ie5ND2b9-CqF761_RrDe94YcDL7SaW_VYI5qwuNFQOAY&usqp=CAU`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 19,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRotpjgfwJc8fw7E51ZPn_YfYyETN5xHujgaw&s`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 20,
    category: "Men",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 20,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://stylishlyme.com/wp-content/uploads/2015/09/Business-Casual-for-Women-Clothing-Guide.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 21,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://i.pinimg.com/474x/c3/be/29/c3be29cbf7416d1b8eced0ba4392593d.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 22,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://i.pinimg.com/236x/03/04/7b/03047bdd07c3f9d2949609014f92eead.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 23,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://i.pinimg.com/236x/66/7d/4c/667d4ceb07368a4fa84496ec05113c16.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 24,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://mikadopersonalstyling.com/wp-content/uploads/2020/06/womens-fashion-tips.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 25,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://officesalt.com/wp-content/uploads/2018/05/12TRENDY-WORK-OUTFITS-FOR-BUSINESS-WOMEN.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 26,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://i.pinimg.com/474x/42/8b/d5/428bd53aed20b0c333c9812b1ddb9570.jpg`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 27,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://adrift.com.au/cdn/shop/articles/unnamed_11_d98e1778-a673-4321-8f9b-2651cadd3ad8.jpg?v=1753683130`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 28,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://media.johnlewiscontent.com/i/JohnLewis/ww-block18-130625-v1?fmt=auto`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 29,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG-SxV7AafzYd6ieqog3z46yBZY-GiFr8KLg&s`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 30,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLHkbMIsqBZW7fF8bKOHs9J9tt3rnHS09d2Q&s`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 31,
    category: "Women",
    name: "Striped Flutter Sleeve Overtop Collor Peplum Hem Blouse",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9igzce8KZlERMQ9NbVZIAvKIt8vEBjTdHAQ&s`,
    lowPrice: 55.99,
    heightPrice: 190,
  },
  {
    id: 32,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://i.pinimg.com/236x/94/1e/b7/941eb773d4de289124497ece181f3d9d.jpg`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 33,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRotpjgfwJc8fw7E51ZPn_YfYyETN5xHujgaw&s`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 34,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 35,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://i.pinimg.com/236x/94/1e/b7/941eb773d4de289124497ece181f3d9d.jpg`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 36,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9QFutiU9xa23VqhTo5zoe-b4Ie5ND2b9-CqF761_RrDe94YcDL7SaW_VYI5qwuNFQOAY&usqp=CAU`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 37,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRotpjgfwJc8fw7E51ZPn_YfYyETN5xHujgaw&s`,
    lowPrice: 78.33,
    heightPrice: 108.33,
  },
  {
    id: 38,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 108.33,
  },
  {
    id: 39,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 108.33,
  },
  {
    id: 40,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 108.33,
  },
  {
    id: 41,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 108.33,
  },
  {
    id: 42,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 108.33,
  },
  {
    id: 43,
    category: "Kids",
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    image: `https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/58/1279072/1.jpg?5578`,
    lowPrice: 32.31,
    heightPrice: 108.33,
  },
]);

export default Dataproduct;
